export interface Suite {
    id: string;
    name: string;
    shortDescription: string;
    meters: number;
    persons: number;
    bathroom: number;
    bed: number;
    price: number;
    amenities: string[];
    images: string[]; // use public asset paths to avoid many imports
    noAmenities: string[];
}

export const suites: Suite[] = [
    {
        id: "suite-1",
        name: "Suíte Esperança 01",
        shortDescription:
            "A cama king e o ar-condicionado garantem o conforto da suíte. A TV Smart com Netflix oferece entretenimento...",
        meters: 30,
        persons: 2,
        bathroom: 1,
        bed: 1,
        price: 250,
        amenities: [
            "Xampu",
            "Sabonete para o corpo",
            "Água quente",
            "Cabides",
            "Roupa de cama",
            "Cobertor e travesseiros extras",
            "Local para guardar as roupas",
            "Wi-fi",
            "TV",
            "Ar-condicionado",
            "Tranca na porta do quarto",
            "Cafeteira elétrica",
            "Permitido fumar",
            "Refrigerador",
            "Cadeiras",
            "Pet friendly",
        ],
        // coloque as imagens em public/suites/suite-1/ e referencie pelo caminho público
        images: [
            "/suites/suite1/example1.avif",
            "/suites/suite1/example2.avif",
            "/suites/suite1/example3.avif",
        ],
        noAmenities: [
            "Secador de cabelo",
            "Cofre",
            "Banheira",
            "Micro-ondas",
            "Cozinha completa",
            "Máquina de lavar",
            "Ferro de passar roupas",
            "Detector de fumaça",
            "Extintor de incêndio",
        ],
    },
    {
        id: "suite-2",
        name: "Suíte Esperança 2",
        shortDescription:
            "Uma cama confortável, ar-condicionado e uma Smart TV com Netflix aumentam o apelo do quarto. Uma mesa de centro...",
        meters: 30,
        persons: 2,
        bathroom: 1,
        bed: 1,
        price: 250,
        amenities: [
            "Xampu",
            "Sabonete para o corpo",
            "Água quente",
            "Cabides",
            "Roupa de cama",
            "Cobertor e travesseiros extras",
            "Local para guardar as roupas",
            "Wi-fi",
            "TV",
            "Ar-condicionado",
            "Tranca na porta do quarto",
            "Cafeteira elétrica",
            "Permitido fumar",
            "Refrigerador",
            "Cadeiras",
            "Pet friendly",
        ],
        // coloque as imagens em public/suites/suite-1/ e referencie pelo caminho público
        images: [
            "/suites/suite2/example1.avif",
            "/suites/suite2/example2.avif",
        ],
        noAmenities: [
            "Secador de cabelo",
            "Cofre",
            "Banheira",
            "Micro-ondas",
            "Cozinha completa",
            "Máquina de lavar",
            "Ferro de passar roupas",
            "Detector de fumaça",
            "Extintor de incêndio",
        ],
    },
    {
        id: "suite-3",
        name: "Suíte Esperança 3",
        shortDescription:
            "A Suíte 3 é ideal para até três pessoas que buscam conforto e tranquilidade em meio à natureza. Ampla e acolhedora...",
        meters: 30,
        persons: 3,
        bathroom: 1,
        bed: 2,
        price: 250,
        amenities: [
            "Xampu",
            "Sabonete para o corpo",
            "Água quente",
            "Cabides",
            "Roupa de cama",
            "Cobertor e travesseiros extras",
            "Local para guardar as roupas",
            "Wi-fi",
            "TV",
            "Ar-condicionado",
            "Tranca na porta do quarto",
            "Cafeteira elétrica",
            "Permitido fumar",
            "Refrigerador",
            "Cadeiras",
            "Pet friendly",
        ],
        // coloque as imagens em public/suites/suite-1/ e referencie pelo caminho público
        images: [
            "/suites/suite3/example1.avif",
            "/suites/suite3/example2.avif",
            "/suites/suite3/example3.avif",
            "/suites/suite3/example4.avif",
        ],
        noAmenities: [
            "Secador de cabelo",
            "Cofre",
            "Banheira",
            "Micro-ondas",
            "Cozinha completa",
            "Máquina de lavar",
            "Ferro de passar roupas",
            "Detector de fumaça",
            "Extintor de incêndio",
        ],
    },
    {
        id: "suite-4",
        name: "Suíte Esperança 4",
        shortDescription:
            "A cama confortável e o ar-condicionado garantem o conforto do quarto. A TV Smart com Netflix e o frigobar, junto à...",
        meters: 30,
        persons: 2,
        bathroom: 1,
        bed: 1,
        price: 250,
        amenities: [
            "Xampu",
            "Sabonete para o corpo",
            "Água quente",
            "Cabides",
            "Roupa de cama",
            "Cobertor e travesseiros extras",
            "Local para guardar as roupas",
            "Wi-fi",
            "TV",
            "Ar-condicionado",
            "Tranca na porta do quarto",
            "Cafeteira elétrica",
            "Permitido fumar",
            "Refrigerador",
            "Cadeiras",
            "Pet friendly",
        ],
        // coloque as imagens em public/suites/suite-1/ e referencie pelo caminho público
        images: [
            "/suites/suite4/example1.avif",
            "/suites/suite4/example2.avif",
            "/suites/suite4/example3.avif",
            "/suites/suite4/example4.avif",
        ],
        noAmenities: [
            "Secador de cabelo",
            "Cofre",
            "Banheira",
            "Micro-ondas",
            "Cozinha completa",
            "Máquina de lavar",
            "Ferro de passar roupas",
            "Detector de fumaça",
            "Extintor de incêndio",
        ],
    },
    {
        id: "suite-5",
        name: "Suíte Esperança 5",
        shortDescription:
            "Com dois quartos, a suíte acomoda até quatro pessoas, garantindo conforto e privacidade. A varanda com rede oferece...",
        meters: 30,
        persons: 4,
        bathroom: 1,
        bed: 2,
        price: 250,
        amenities: [
            "Xampu",
            "Sabonete para o corpo",
            "Água quente",
            "Cabides",
            "Roupa de cama",
            "Cobertor e travesseiros extras",
            "Local para guardar as roupas",
            "Wi-fi",
            "TV",
            "Ar-condicionado",
            "Tranca na porta do quarto",
            "Cafeteira elétrica",
            "Permitido fumar",
            "Refrigerador",
            "Cadeiras",
            "Pet friendly",
        ],
        // coloque as imagens em public/suites/suite-1/ e referencie pelo caminho público
        images: [
            "/suites/suite5/example1.avif",
            "/suites/suite5/example2.avif",
            "/suites/suite5/example3.avif",
            "/suites/suite5/example4.jpeg",
            "/suites/suite5/example5.avif",
        ],
        noAmenities: [
            "Secador de cabelo",
            "Cofre",
            "Banheira",
            "Micro-ondas",
            "Cozinha completa",
            "Máquina de lavar",
            "Ferro de passar roupas",
            "Detector de fumaça",
            "Extintor de incêndio",
        ],
    },
    {
        id: "suite-6",
        name: "Suíte Chalé Esperança",
        shortDescription:
            "No térreo, o quarto oferece uma cama super king, sofá-cama, mesa de café, TV Smart de 43 polegadas, banheiro completo...",
        meters: 30,
        persons: 8,
        bathroom: 1,
        bed: 5,
        price: 500,
        amenities: [
            "Xampu",
            "Sabonete para o corpo",
            "Água quente",
            "Cabides",
            "Roupa de cama",
            "Cobertor e travesseiros extras",
            "Local para guardar as roupas",
            "Wi-fi",
            "TV",
            "Ar-condicionado",
            "Tranca na porta do quarto",
            "Cafeteira elétrica",
            "Permitido fumar",
            "Refrigerador",
            "Cadeiras",
            "Pet friendly",
        ],
        // coloque as imagens em public/suites/suite-1/ e referencie pelo caminho público
        images: [
            "/suites/suite6/example1.avif",
            "/suites/suite6/example2.avif",
            "/suites/suite6/example3.avif",
            "/suites/suite6/example4.avif",
            "/suites/suite6/example5.avif",
            "/suites/suite6/example6.avif",
        ],
        noAmenities: [
            "Secador de cabelo",
            "Cofre",
            "Banheira",
            "Micro-ondas",
            "Cozinha completa",
            "Máquina de lavar",
            "Ferro de passar roupas",
            "Detector de fumaça",
            "Extintor de incêndio",
        ],
    },
];